# Generated by Django 2.1.4 on 2018-12-22 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TVShow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('release_year', models.IntegerField()),
                ('tvdb_id', models.IntegerField()),
            ],
        ),
    ]
