# Generated by Django 2.1.4 on 2019-02-02 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tv_series', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TVShow',
            new_name='TVSeries',
        ),
    ]
